DECISION_APPROVE = "APPROVE"
DECISION_BLOCK = "BLOCK"
DECISION_STEP_UP = "STEP_UP"

AGENT_ACTIVE = "ACTIVE"
AGENT_SUSPENDED = "SUSPENDED"
AGENT_EXPIRED = "EXPIRED"

TRANSACTION_PENDING = "PENDING"
TRANSACTION_APPROVED = "APPROVED"
TRANSACTION_BLOCKED = "BLOCKED"
TRANSACTION_STEP_UP = "STEP_UP"
TRANSACTION_COMPLETED = "COMPLETED"
TRANSACTION_FAILED = "FAILED"